blog/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('', views.homepage, name="homepage"),

    path('blog/', views.ArticleListView.as_view(), name="article-list"),
    path('blog/<slug:slug>/', views.ArticleDetailView.as_view(), name="article-detail"),
    path('post/', views.create_new_article, name="create-new-article"),

    path('register/', views.register_page, name="registering"),

    path('auth/login/', LoginView.as_view(), name="login"),
    path('auth/logout/', LogoutView.as_view(), name="logout"),

    path('auth/password-reset/', PasswordResetView.as_view(), name="password-reset"),
    path('auth/password-reset/done/', PasswordResetDoneView.as_view(), name="password-reset-done"),
    path('auth/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path('auth/reset/done/', PasswordResetCompleteView.as_view(), name="password-reset-complete"),
]

personalblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from pytils.translit import slugify


class Article(models.Model):
    """
    Article model. Include title, intro, main text and publication/update date.
    """
    author = models.ForeignKey(User, related_name="articles", on_delete=models.CASCADE)
    article_title = models.CharField("Article title", max_length=255, unique=True, db_index=True)
    intro = models.TextField("Article intro", blank=True, db_index=True)
    text = models.TextField("Article text", db_index=True)
    publication_date = models.DateTimeField("Publication date", auto_now_add=True)
    update_date = models.DateTimeField("Update date", auto_now=True)
    slug = models.SlugField("URL", max_length=255, unique=True, db_index=True)
    like = models.PositiveIntegerField("Likes", default=0)
    dislike = models.PositiveIntegerField("Dislikes", default=0)

    def __str__(self):
        return self.article_title

    def save(self, *args, **kwargs):
        """
        Automatically generates a slug based on the article title.
        """
        self.slug = slugify(self.article_title)
        super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-update_date", "-publication_date"]
        verbose_name = "Article"
        verbose_name_plural = "Articles"


class Comment(models.Model):
    """
    Comments model.
    """
    article = models.ForeignKey(Article, related_name="comments", on_delete=models.CASCADE)
    comment_text = models.TextField(max_length=255, help_text="Comment")
    username = models.CharField(max_length=255, help_text="Username")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'A comment belonging to "{self.article.article_title}" article'

    class Meta:
        ordering = ['-comment_date']
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Article


class RegisterUserForm(UserCreationForm):
    """
    Registration form. Include Username, Email, Password1, Password2 fields.
    """
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class CreateNewArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["article_title", "intro", "text"]

blog/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import generic

from .models import Article
from .forms import RegisterUserForm, CreateNewArticleForm


def homepage(request):
    """
    Returns simple home page.
    """
    return render(request, "blog/homepage.html")


class ArticleListView(generic.ListView):
    """
    Displays list of all articles with pagination.
    """
    model = Article
    paginate_by = 5
    template_name = "blog/article_list.html"
    context_object_name = "articles"


class ArticleDetailView(generic.DetailView):
    """
    Displays detailed page of particular article.
    """
    model = Article
    template_name = "blog/article_detail.html"


def register_page(request):
    """
    Returns the new user registration form.
    """
    form = RegisterUserForm()
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            messages.success(request, f'Welcome {user}!')
            return redirect("blog:login")
    context = {"form": form}
    return render(request, "registration/register.html", context)


def create_new_article(request):
    """
    Displays a form for creating a new article.
    """
    form = CreateNewArticleForm()
    if request.method == "POST":
        form = CreateNewArticleForm(request.POST)
        article = form.save(commit=False)
        article.author = request.user
        if form.is_valid():
            form.save()
            messages.success(request, 'New article added.')
            return redirect("blog:article-detail", slug=article.slug)
    context = {"form": form}
    return render(request, "blog/create_article.html", context)

blog/templates/accounts/register.html
{% extends 'blog/homepage.html' %}

{% block content %}
<div class="container-md justify-content-center mt-3">
    <div class="text-center"><h4>REGISTER ACCOUNT</h4></div>
    <div class="container-max">

        <form method="POST" class="list-group-item border-0">
        {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                {{ field }}
            </div>
            <div id="passwordHelpBlock" class="form-text">
                {{ field.errors }}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-between align-items-center">
            <button type="submit" class="btn btn-primary" name="Create User">Register</button>
            <div>Already have an account? <a href="{% url 'blog:logging' %}">Login</a></div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'blog/homepage.html' %}

{% block title %}{{ article.article_title }}{% endblock %}

{% block content %}
<div class="d-flex justify-content-center mt-4">
    <div class="container-max">
        <h6 class="card-subtitle mb-2 text-muted">{{ article.intro }}</h6>
        <br>
        <p class="card-text">{{ article.text }}</p>
        <small>{{ article.publication_date }}</small>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'blog/homepage.html' %}
{% load static %}
{% block title %}Articles List{% endblock %}

{% block content %}
<!--Search line-->
<div class="d-flex justify-content-center mt-3">
    <form class="d-flex w-50 container-max" role="search">
        <input class="form-control me-2" type="search" placeholder="Author or title..." aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Find</button>
    </form>
</div>
<!--Article instance-->
<div class="container-md justify-content-center mt-3">
    <div class="container-max">
        <nav aria-label="Page navigation example">
        {% for article in articles %}
            <div class="list-group mb-3">
                <a href="{% url 'blog:article-detail' article.slug %}" class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-2">{{ article.article_title }}</h5>
                        <small>{{ article.publication_date }}</small>
                    </div>
                    <p class="mb-2">{{ article.intro }}</p>
                    <div class="d-flex w-100 justify-content-between">
                        <small>Author: {{ article.author }}</small>
                        <small>
                            <img src="{% static 'blog/icons/like.png' %}" width="17px"> {{ article.like }}
                            <img src="{% static 'blog/icons/dislike.png' %}" width="17px"> {{ article.dislike }}
                        </small>
                    </div>
                </a>
            </div>
        {% endfor %}
<!--Paginator-->
        {% if is_paginated %}
            <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>
            {% endif %}

            {% for page in paginator.page_range %}
                {% if page_obj.number == page %}
                    <li class="page-item"><a class="page-link active">{{ page }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Next</a>
                </li>
            {% endif %}
            </ul>
        {% endif %}
        </nav>
    </div>
</div>
{% endblock %}

blog/templates/blog/create_article.html
{% extends 'blog/homepage.html' %}
{% load widget_tweaks %}

{% block title %}Create New Article{% endblock %}

{% block content %}
<div class="container-md justify-content-center mt-3">
    <div class="text-center"><h4>Create New Article</h4></div>
    <div class="container-max">
        <form method="POST" class="list-group-item border-0">
        {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                {% if field.name == 'intro' %}
                {% render_field field class+="form-control" placeholder=field.label rows=3 %}
                {% else %}
                {% render_field field class+="form-control" placeholder=field.label %}
                {% endif %}
            </div>
            <div id="passwordHelpBlock" class="form-text">
                {{ field.errors }}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-between align-items-center">
                <button type="submit" class="btn btn-primary" name="Post">Post</button>
                <a class="btn btn-outline-danger" href="#">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous">
    </script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'blog/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'blog/icons/favicon.ico' %}" type="image/x-icon">
    <meta charset="UTF-8">
    <title>{% block title %}Personal Blog{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-light bg-light border-bottom">
        <div class="container-md">
            <a class="navbar-brand" href="{% url 'blog:article-list' %}">
                <img src="{% static 'blog/icons/blogicon.png' %}"
                     alt="To the homepage" width="30" height="24"
                     class="d-inline-block align-text-top">
                {{ user.username|default:'Personal Blog' }}
            </a>
            {% if user.is_authenticated %}
            <div class="d-flex">
                <a class="btn btn-outline-success" href="{% url 'blog:create-new-article' %}">Create new article</a>
                <a class="btn btn-outline-danger" href="{% url 'blog:logout' %}">Log Out</a>
            </div>
            {% else %}
            <div class="d-flex">
                <a class="btn btn-link" href="{% url 'blog:login' %}">Log In</a>
                <a class="btn btn-outline-success" href="{% url 'blog:registering' %}">Register</a>
            </div>
            {% endif %}
        </div>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>